baseURL = "https://weyland-yutani.proffer.dev"
languageCode = "en-us"
title = "Weyland-Yutani Corp"
theme = "weyland-yutani"

[params]
  description = "The Weyland-Yutani Corporation specializes in and develops major advancements in technology, such as off-world colonization."
  subTitle = "Building Better Worlds"
  currentOperation = "Acheron"
  founded = "2157"
  colonists = "158"
  images = ["/images/weyland-yutani-social.jpg"]

[menu]

  [[menu.main]]
    identifier = "careers"
    name = "Careers"
    url = "/careers/"
    weight = 1

  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 3

  [[menu.required]]
    identifier = "privacy-policy"
    name = "Privacy Policy"
    url = "/privacy-policy/"
    weight = 1

  [[menu.required]]
    identifier = "copyright"
    name = "Copyright"
    url = "/copyright/"
    weight = 2

  [[menu.required]]
    identifier = "terms-of-use"
    name = "Terms of Use"
    url = "/terms-of-use/"
    weight = 3

  [[menu.info]]
    identifier = "site-map"
    name = "Site Map"
    url = "/site-map/"
    weight = 1

  [[menu.info]]
    identifier = "compatibility"
    name = "Compatibility"
    url = "/compatibility/"
    weight = 2

  [[menu.info]]
    identifier = "repository"
    name = "Repository"
    url = "https://github.com/jacobproffer/weyland-yutani"
    weight = 3
