name = "Weyland-Yutani"
license = "Apache 2.0"
licenselink = "https://github.com/jacobproffer/weyland-yutani/blob/master/LICENSE"
description = "A Weyland-Yutani Hugo theme with careers and news post types."
homepage = "https://weyland-yutani.proffer.dev/"
tags = ["aliens", "news", "articles", "careers"]
features = ["careers", "news"]
min_version = "0.54"

[author]
  name = "Jacob Proffer"
  homepage = "https://proffer.dev/"
